##code for figure 1
library(ggplot2)
library(ggpubr)
library(foreign)
library(scales)

#figure 1a
g1<-ggplot(data=mydata[mydata$countryname =="United Kingdom" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("UK") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g2<-ggplot(data=mydata[mydata$countryname =="United States" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("US") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.15,color="red")
g3<-ggplot(data=mydata[mydata$countryname =="France" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("France") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g4<-ggplot(data=mydata[mydata$countryname =="Italy" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Italy") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g5<-ggplot(data=mydata[mydata$countryname =="Brazil" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Brazil") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g6<-ggplot(data=mydata[mydata$countryname =="Germany" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Germany") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g7<-ggplot(data=mydata[mydata$countryname =="Iran" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Iran") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g8<-ggplot(data=mydata[mydata$countryname =="Canada" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Canada") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g9<-ggplot(data=mydata[mydata$countryname =="Australia" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Australia") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.4,color="red")
g10<-ggplot(data=mydata[mydata$countryname =="Japan" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Japan") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g11<-ggplot(data=mydata[mydata$countryname =="Egypt" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("Egypt") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.1,color="red")
g12<-ggplot(data=mydata[mydata$countryname =="China" & mydata$epi_year <2022 & is.na(mydata$regionname)==TRUE,], aes(x=death)) +geom_point(aes(y = response),shape=21, fill="blue",size=3)+ ggtitle("China") +xlab("Total death per million (past 3 weeks)") + ylab("Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,1000))+ylim(0,85)+stat_smooth(aes(y=response),geom='line', alpha=0.7, se=FALSE,span=0.2,color="red")
ggarrange(g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12, ncol = 4, nrow = 3)                                                                                                                                                                                                                              

#figure 1b
f12<-ggplot(mydata2, aes(x= raw_death, y = fitted)) + geom_point(shape=21, fill="purple",size=3)+xlab("Total death per million (past 3 weeks)") + ylab("Estimated Government Response")+theme_classic() +scale_x_continuous(trans='log10',limits=c(1,10^2.5))+ylim(0,85)
